name: tesis-sapienza
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - libffi=3.4.4
  - openssl=3.0.12
  - pip=23.3.1
  - python=3.11.5
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tk=8.6.12
  - tzdata=2023c
  - wheel=0.41.2
  - xz=5.4.5
  - zlib=1.2.13
  - pip:
      - affine==2.4.0
      - attrs==23.2.0
      - certifi==2023.11.17
      - click==8.1.7
      - click-plugins==1.1.1
      - cligj==0.7.2
      - fiona==1.9.5
      - numpy==1.26.2
      - opencv-python==4.9.0.80
      - pyparsing==3.1.1
      - rasterio==1.3.9
      - shapely==2.0.2
      - six==1.16.0
      - snuggs==1.4.7
